# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: 'github-actions'
    target-branch: 'develop'
    directory: '/'
    schedule:
      interval: 'daily'

  # Enable version updates for Terraform wings
  - package-ecosystem: 'terraform'
    target-branch: 'develop'
    directory: '/terraform/wings'
    schedule:
      interval: 'daily'

  # Enable version updates for npm packages
  - package-ecosystem: 'npm'
    target-branch: 'develop'
    directory: '/'
    schedule:
      interval: 'daily'