# Create Node location in Pterodactyl Panel
resource "restapi_object" "pterodactyl_location" {
  path = "/api/application/locations"
  data = jsonencode({
    "short" : "CloudLAN",
    "long" : "CloudLAN autogenerated location",
  })
}

# Create Node in Pterodactyl Panel
resource "restapi_object" "pterodactyl_node" {
  path = "/api/application/nodes"
  data = jsonencode({
    "name" : "New Node",
    "location_id" : "${restapi_object.pterodactyl_location.id}",
    "fqdn" : "${var.node_fqdn}",
    "scheme" : "https",
    "memory" : 6240,
    "memory_overallocate" : 0,
    "disk" : 50000,
    "disk_overallocate" : 0,
    "upload_size" : 100,
    "daemon_sftp" : 2022,
    "daemon_listen" : 8080
  })

  depends_on = [
    restapi_object.pterodactyl_location
  ]
}
