# Create Node location in Pterodactyl Panel
resource "restapi_object" "pterodactyl_location" {
  path = "/api/application/locations"
  data = jsonencode({
    "short" : "CloudLAN",
    "long" : "CloudLAN autogenerated location",
  })
}

module "wing-node" {
  source = "./tf-modules/wing-node"

  // Values unique to each node
  for_each         = var.servers
  dns_a_record     = each.key
  node_name        = each.key
  node_server_type = each.value.type
  node_location    = each.value.location
  node_memory      = each.value.memory
  node_disk        = each.value.disk

  // General values
  dns_domain_name = var.dns_domain_name

  pterodactyl_panel_url     = var.pterodactyl_panel_url
  pterodactyl_panel_api_key = var.pterodactyl_panel_api_key

  letsencrypt_email = var.letsencrypt_email

  pterodactyl_wings_location_id = restapi_object.pterodactyl_location.id

  depends_on = [
    restapi_object.pterodactyl_location
  ]
}
