# Create Node location in Pterodactyl Panel
resource "restapi_object" "pterodactyl_location" {
  path = "/api/application/locations"
  data = jsonencode({
    "short" : "CloudLAN",
    "long" : "CloudLAN autogenerated location",
  })
}

module "wing-node" {
  source = "./tf-modules/wing-node"

  pterodactyl_panel_url     = var.pterodactyl_panel_url
  pterodactyl_panel_api_key = var.pterodactyl_panel_api_key

  node_fqdn         = var.domain
  letsencrypt_email = var.letsencrypt_email

  pterodactyl_wings_location_id = restapi_object.pterodactyl_location.id

  depends_on = [
    restapi_object.pterodactyl_location
  ]
}
