#cloud-config
users:
  - name: ${username}
    groups: users, admin, docker, wings
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}
packages:
  - fail2ban
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - nano
  - certbot
package_update: true
package_upgrade: true
runcmd:
  # Fail2ban config
  - cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  # SSHD config
  - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers ${username}' /etc/ssh/sshd_config
  # Pterodactyl install
  - mkdir -p /etc/pterodactyl
  - chown root:wings -R /etc/pterodactyl
  - curl -L -o /usr/local/bin/wings https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_amd64
  - chown root:wings /usr/local/bin/wings
  - chmod u+x /usr/local/bin/wings
  - chmod g+x /usr/local/bin/wings
  # Waiting for DNS to propagate
  - IP=$(curl -s http://ipv4.icanhazip.com/); while [ "$(dig +short ${domain})" != "$IP" ]; do echo "Waiting for DNS to propagate"; sleep 5; done
  - echo "DNS has propagated"  
  # Setting up SSL
  - certbot certonly --standalone --agree-tos --no-eff-email --email ${email} -d ${domain}
  # Configuring wings
  - wings configure --panel-url ${pterodactyl_panel_url} --token ${pterodactyl_panel_api_key} --node ${node_id}
  # Finishing up
  - systemctl enable wings
  - reboot
write_files:
  - path: /etc/systemd/system/wings.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Pterodactyl Wings Daemon
      After=docker.service
      Requires=docker.service
      PartOf=docker.service

      [Service]
      User=root
      WorkingDirectory=/etc/pterodactyl
      LimitNOFILE=4096
      PIDFile=/var/run/wings/daemon.pid
      ExecStart=/usr/local/bin/wings
      Restart=on-failure
      StartLimitInterval=180
      StartLimitBurst=30
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
